name: aws-cdk-stagr-app-on-pr

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "aws_cdk/aws-cdk-stagr-app/**"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 141991823339

defaults:
  run:
    working-directory: aws-cdk-stage-app

jobs:
  dev:
    # this ensures the job ONLY runs when PR targets main/master
    if: >
      github.event.pull_request.base.ref == 'main' ||
      github.event.pull_request.base.ref == 'master'
    name: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.X"

      - name: Install AWS CDK Globally
        run: npm install -g aws-cdk

      - name: Install Dependencies
        run: npm run prep

      - name: Build Project
        run: npm run build

      - name: Configure AWS Credentials (DEV)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Conditional CDK Bootstrap
        run: |
          if aws cloudformation describe-stacks --stack-name CDKToolkit >/dev/null 2>&1; then
            echo "CDK already bootstrapped. Skipping bootstrap..."
          else
            echo "CDK not bootstrapped. Running bootstrap..."
            npm run bootstrap
          fi

      - name: Deploy DEV Stack
        run: npm run deploy:dev
